### ISSUE TITLE
[BUG] Unable to get arbitrage opportunity 

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/gateway-api#133]
- uniswap `WETH-DAI` binance `ETH-USDT`
   - throws error
   - unable to show Profitability
   - also the price from uniswap are not showing
<img width="1680" alt="Screen Shot 2021-08-14 at 8 29 16 AM" src="https://user-images.githubusercontent.com/54516858/129429749-d66917f7-35a0-4409-91cf-c72f59ae031e.png">

```
2021-08-14 00:29:17,700 - 35379 - hummingbot.connector.connector.uniswap.uniswap_connector - WARNING - '<' not supported between instances of 'decimal.Decimal' and 'dict'
2021-08-14 00:29:19,437 - 35379 - hummingbot.connector.connector.uniswap.uniswap_connector - NETWORK - Error getting quote price for WETH-DAI  buy order for 0.02 amount.
Traceback (most recent call last):
  File "/home/ubuntu/hummingbot/hummingbot/core/utils/__init__.py", line 15, in memoize
    return cache[key]
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/cachetools/ttl.py", line 82, in __getitem__
    return self.__missing__(key)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/cachetools/cache.py", line 68, in __missing__
    raise KeyError(key)
KeyError: "((<hummingbot.connector.connector.uniswap.uniswap_connector.UniswapConnector object at 0x7f6a1cbe5340>, 'WETH-DAI', True, Decimal('0.02')), {})"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/hummingbot/hummingbot/connector/connector/uniswap/uniswap_connector.py", line 217, in get_quote_price
    exceptions = check_transaction_exceptions(account_standing)
  File "/home/ubuntu/hummingbot/hummingbot/core/utils/ethereum.py", line 60, in check_transaction_exceptions
    if eth_balance < gas_cost:
TypeError: '<' not supported between instances of 'decimal.Decimal' and 'dict'
2021-08-14 00:29:19,437 - 35379 - hummingbot.connector.connector.uniswap.uniswap_connector - WARNING - '<' not supported between instances of 'decimal.Decimal' and 'dict'
```

- balancer `DAI-USDC` binance `USDC-USDT`
    - unable to show Profitability 
   - price from balancer are not showing
<img width="1680" alt="Screen Shot 2021-08-14 at 8 44 55 AM" src="https://user-images.githubusercontent.com/54516858/129429836-b83c1117-5bce-4b1b-9830-b2a1fb6a2ffd.png">
  
 - no arbitrage opportunity when using `WETH-DAI`
    - unable to show Profitability
    - price from balancer are not showing
<img width="1680" alt="Screen Shot 2021-08-14 at 8 48 52 AM" src="https://user-images.githubusercontent.com/54516858/129429910-29488c02-5d7e-4313-9f1c-618133678071.png">

- Logs and configs:
[amm.zip](https://github.com/CoinAlpha/gateway-api/files/6985711/amm.zip)

Client version: 0.42.0
Gateway version: 0.8.0

**Comment by PtrckM** [comment]
FYI: Traceback and found b7e2b416def592cc3a67b578a17d6ad6a42b04ec working for uniswap only.
<img width="1680" alt="Screen Shot 2021-08-14 at 9 32 12 AM" src="https://user-images.githubusercontent.com/54516858/129430604-4ecb292f-2f24-4311-846b-6493c0fbaa8b.png">

**Comment by mifeng** [comment]
I am also seeing this bug - it looks like it was introduced in the gas changes after commit `b7e2b41`:
https://github.com/CoinAlpha/gateway-api/compare/b7e2b41..master

**Comment by vic-en** [comment]
So far, I cannot reproduce this problem.
From inspecting the files from Patrick, I see this error would only occur when the gateway doesn't return a proper response when fetching price which could be due to issues with network or config parameters.

@mifeng I'd like to see your logs if this issue persists on your end.

**Comment by mifeng** [comment]
@vic-en Here's my log file: [logs_conf_amm_arb_2.log](https://github.com/CoinAlpha/gateway-api/files/7015898/logs_conf_amm_arb_2.log)

This appears to be the relevant error:
```
Traceback (most recent call last):
  File "/Users/feng/Code/hummingbot/hummingbot/connector/connector/uniswap/uniswap_connector.py", line 217, in get_quote_price
    exceptions = check_transaction_exceptions(account_standing)
  File "/Users/feng/Code/hummingbot/hummingbot/core/utils/ethereum.py", line 60, in check_transaction_exceptions
    if eth_balance < gas_cost:
TypeError: '<' not supported between instances of 'decimal.Decimal' and 'dict'
2021-08-18 17:33:06,601 - 3737 - hummingbot.connector.connector.uniswap.uniswap_connector - WARNING - '<' not supported between instances of 'decimal.Decimal' and 'dict'
2021-08-18 17:33:08,257 - 3737 - hummingbot.connector.connector.uniswap.uniswap_connector - NETWORK - Error getting quote price for WETH-DAI  sell order for 0.02 amount.
Traceback (most recent call last):
  File "/Users/feng/anaconda3/envs/hummingbot/lib/python3.8/site-packages/cachetools/cache.py", line 39, in __getitem__
    return self.__data[key]
KeyError: "((<hummingbot.connector.connector.uniswap.uniswap_connector.UniswapConnector object at 0x7ff0d8d6a9a0>, 'WETH-DAI', False, Decimal('0.02')), {})"
```

If you're not seeing this, it's likely due to a difference in our Gateway environments. I'll try running this on a fresh VM and see if I can isolate the difference.
